[package]
name = "client-shared"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0"

[dependencies.iced]
version = "0.14"
default-features = false
features = ["advanced", "wgpu"]

[dependencies.shared]
path = "../shared"
